spring:
  spring:
    jpa:
      hibernate:
        ddl-auto: create-drop
        use-new-id-generator-mappings: true
      show-sql: true
      database-platform: org.hibernate.dialect.MariaDB10Dialect
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/jobms?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
logging:
  file:
    path: /log
    name: jobms.log